### ISSUE TITLE
Multiple solutions returned by Mosek

### ISSUE THREAD

**Issue by denisrosset** [vsdp/vsdp-2018#1]
When using the default parameters for Mosek, the output structure contains both the solution of the interior-point algorithm and the result of the basis identification procedure.

In some of our tests (with @roujiawen) however, the basis identification procedure did not lead to better bounds.

If I'm not mistaken, the current VSDP code uses always the IP solution (see https://github.com/vsdp/vsdp-2018/blob/fc4afff454f6371016cb731b497e6ab36c715f2e/%40vsdp/solve_mosek.m#L103 )

**Comment by siko1056** [comment]
This is correct, we currently use only the IP solution at the moment.  Mr. Jansson indicated interest in using VSDP in combination with MOSEK, thus I spent some time to make this happen.  Thank you for being my first users.

Admittedly, I am no MOSEK expert.  Following the [MOSEK user guide on semidefinite optimization][1] and [MOSEK reference][2] I thought the `res.sol.itr` solution is the only one that matters.  Is it always required to check for multiple solutions, e.g. `res.sol.bas` and which one is to favor then?  The output `res.sol.int` seems to make no sense for VSDP, as we do not explicitly check for integer variables.

In my tiny example from Borchers and other small ones from the SDPLIB, `res.sol.bas` is not returned:

```Matlab
A = [3, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0;
  0, 0, 0, 0, 3, 0, 1, 0, 4, 0, 1, 0, 5, 0, 0, 0, 1];
c = [-2; -1; -1; -2; -3; 0; -1; 0; -2; 0; -1; 0; -3; 0; 0; 0; 0];
b = [1; 2];
K.s = [2; 3; 2];
obj = vsdp (A, b, c, K);
obj.solve_mosek ()
``` 

[1]: https://docs.mosek.com/8.1/toolbox/tutorial-sdo-shared.html
[2]: https://docs.mosek.com/8.1/toolbox/data-types.html#solver_solutions

**Comment by denisrosset** [comment]
Indeed, `res.sol.bas` is used only for LP problems! Although we found that basis identification returns more precise results (as indicated by the usual error measures), we have seen that the VSDP results are worse when turning it on.

**Comment by siko1056** [comment]
I see, after some tests with different mixes of cones we can determine when to use `res.sol.bas` in favor of `res.sol.itr`.

**Comment by siko1056** [comment]
Maybe you can check if 2ba2ca9 serves your purpose?  Otherwise I can reopen this item and think about a better way to determine which solution is to prefer.
